### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by schnie** [aries-data/aries-activity-postgres-source#3]
Hey @jlaneve, instead of wrapping the stream up in a promise in here, why not just return the QueryStream?  Looks like its a standard node stream: https://github.com/brianc/node-pg-query-stream/blob/master/index.js#L3.

**Comment by schnie** [comment]
We should remove `fakeFunction` too.

**Comment by jlaneve** [comment]
PR #5 should fix this.

**Comment by jlaneve** [comment]
@benjamingregory can this be closed now? PR was merged.
